### ISSUE TITLE
[BUG] Deployment delay

### ISSUE THREAD

**Issue by nmasi322** [brimblehq/atlas#32]
**Describe the bug**
Hi, I pushed to github but my recent changes have not been deployed. A deployment started 2 hours ago but still has a status of "in progress", please can this be looked into? I'll attach screenshots.

**Screenshots**
This is the deployments after 59mins with a status of "in progress"
<img width="1680" alt="Screenshot 2023-08-05 at 9 43 49 PM" src="https://github.com/brimblehq/atlas/assets/74861009/15fe9962-9466-4475-863f-afa4b938f2e2">

A few seconds later, it starts over again:
<img width="1680" alt="Screenshot 2023-08-05 at 9 44 54 PM" src="https://github.com/brimblehq/atlas/assets/74861009/840e2b46-1fd0-4ba8-8516-dedfe99de5df">

This is where my logs end:
<img width="1680" alt="Screenshot 2023-08-05 at 9 52 03 PM" src="https://github.com/brimblehq/atlas/assets/74861009/dcb3dd15-abd5-46ac-a920-bcacbdfafe16">

**Desktop (please complete the following information):**

- OS: macOs
- Browser Arc

**Comment by klefcodes** [comment]
Hi @nmasi322 thanks for pointing it out, this has just been resolved here https://github.com/brimblehq/atlas/commit/496f707b3c3e2271272d0bfeaf9406978d067a0a

You can redeploy for it to take effect and I will remove the in-progress log so you'll have a cleaner dashboard and experience.

**Comment by nmasi322** [comment]
Hi @klefcodes thank you so much for your help. I was able to successfully deploy my app a few minutes ago. 

But I can't view my deployed website's contents on the url. It shows a blank white page 🥲

**Comment by klefcodes** [comment]
Can you point me to the app link, and let me investigate what could have gone wrong?

**Comment by nmasi322** [comment]
Here => https://the-brownie-factory.brimble.app/

**Comment by klefcodes** [comment]
Seems like the error is from your application itself
<img width="475" alt="Screenshot 2023-08-06 at 10 46 09" src="https://github.com/brimblehq/atlas/assets/30050823/30051a63-0c2e-4187-ab2c-6be4e3e3d3fc">

**Comment by nmasi322** [comment]
Oh 😂
Thank you for your help, I appreciate.
